apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: polupate-db
  name: polupate-db
  namespace: ikomida
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - image: us-central1-docker.pkg.dev/$PROJECT_ID/docker/populate-db-image:latest
          name: polupate-db
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: NODE_ENV
                  optional: false
            - name: IKOMIDA_PRIVATEKEY
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: IKOMIDA_PRIVATEKEY
                  optional: false
            - name: IKOMIDA_PUBLICKEY
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: IKOMIDA_PUBLICKEY
                  optional: false
            - name: GOOGLEADMIN
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: googleAdmin
                  optional: false
            - name: PAGSEGURO_EMAIL
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: PAGSEGURO_EMAIL
                  optional: false
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: DBUSER
            - name: DBPASS
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: DBPASS
            - name: DBNAME
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: DBNAME
            - name: DBHOST
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: DBHOST
            - name: DBPORT
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: DBPORT
            - name: PROJID
              valueFrom:
                secretKeyRef:
                  name: environment
                  key: PROJID
